In [1]:
import pandas
import numpy as np

In [2]:
fr1 = pandas.read_csv('alarm(1).csv')

c:\users\11249\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (44,53) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [3]:
nl=fr1['NE_LABEL']
title=fr1['ALARM_TITLE_TEXT']
et=fr1['EVENT_TIME']
org=fr1['ORG_SEVERITY']

In [4]:
nls={}
numofnls=0
for n_l in nl:
    if n_l not in nls:
        nls[n_l]=numofnls
        numofnls+=1

In [5]:
nls

{'沧源王冷矿区NG17': 0,
 '沧源王冷矿区NG18': 1,
 '沧源王冷矿区NG1': 2,
 'KJ-WX-LIC4020_沧源县王冷矿区一楼无线机房': 3,
 '沧源王冷矿区NG19': 4,
 '沧源县王冷矿区-FHHN': 5,
 '沧源县王冷矿区-FHHN-141': 6,
 '沧源县王冷矿区-FHHN-142': 7,
 '沧源县王冷矿区-FHHN-143': 8,
 '沧源县王冷矿区-FHHN-131': 9,
 '沧源县王冷矿区-FHHN-132': 10,
 '沧源县王冷矿区-FHHN-133': 11}

In [6]:
t={}
numoft=0
for tit in title:
    if tit not in t:
        t[tit]=numoft
        numoft+=1

In [7]:
t

{'MEAN HOLDING TIME BELOW DEFINED THRESHOLD': 0,
 'OBJECT ADMINISTRATIVE STATE CHANGED': 1,
 'TRX RESTARTED': 2,
 'BCCH MISSING': 3,
 'TRX FAULTY': 4,
 'CONFIGURATION OF BCF FAILED': 5,
 'FAR-END ALARM': 6,
 'ALARM INDICATION SIGNAL (AIS) RECEIVED': 7,
 'FREQUENCY ERROR': 8,
 'D-CHANNEL FAILURE': 9,
 'PCM FAILURE': 10,
 '[衍生告警]PCM FAILURE告警超限': 11,
 '基站退服告警': 12,
 'BTS O&amp;M LINK FAILURE': 13,
 'FSU通信中断': 14,
 'LOSS OF SYNCHRONIZATION SIGNAL': 15,
 'RECEIVED BIT ERROR RATIO (BER) &gt; 1E-6': 16,
 'DATABASE FULL': 17,
 'LOSS OF FRAME ALIGNMENT': 18,
 'LOSS OF CRC MULTIFRAME ALIGNMENT': 19,
 'WORKING HALF RATE TCH RATIO BELOW THRESHOLD': 20,
 '[衍生关联]诺西同一2G基站下基站退服+所有小区退服衍生关联': 21,
 'WORKING FULL RATE TCH RATIO BELOW THRESHOLD': 22,
 '[衍生告警][沧源县王冷矿区一楼无线机房]物理站点退服告警': 23,
 'FAILURE IN SENDING SYSTEM INFORMATION TO BTS SITE': 24,
 '[衍生关联]无线同一机房下2G+3G+4G小区退服衍生关联': 25,
 '[衍生告警]跨专业_同一机房无线退服告警': 26,
 'TRX NOTIFICATION': 27,
 'BEATING BTS ALARM': 28,
 'BCF INITIALIZATION': 29,
 '[衍生关联]诺西同一2G基站下单

In [8]:
import re
def gd(line):
    searchObj = re.search( r'(.*?)/(.*?)/(.*?) ', line)
    msd1={1:31,2:28,3:31,4:30,5:31,6:30,7:31,8:31,9:30,10:31,11:30,12:31}
    msd2={1:31,2:28,3:31,4:30,5:31,6:30,7:31,8:31,9:30,10:31,11:30,12:31}
    if searchObj.group(1)=='2019':
        for ms in msd1:
            if int(searchObj.group(2))==ms:
                days=int(searchObj.group(3))-1
                for m in range(1,ms):
                    days+=msd1[m]
                return days*24*60+int(line[-5:-3])*60+int(line[-2:])
    if searchObj.group(1)=='2020':
        for ms in msd2:
            if int(searchObj.group(2))==ms:
                days=int(searchObj.group(3))-1
                for m in range(1,ms):
                    days+=msd2[m]
                return 365*24*60+days*24*60+int(line[-5:-3])*60+int(line[-2:])

In [9]:
time=[]
for i in range(37237):
    time1=gd(et[i])
    time.append(time1)

In [10]:
time

[1210,
 1962,
 1963,
 1963,
 1962,
 1963,
 1962,
 1962,
 3773,
 3763,
 3765,
 3757,
 3757,
 3755,
 3765,
 3765,
 3851,
 3851,
 3784,
 3779,
 3851,
 3947,
 3947,
 3841,
 3841,
 3959,
 3895,
 3977,
 3982,
 3982,
 3745,
 3745,
 3745,
 3744,
 3768,
 4052,
 4052,
 4049,
 3760,
 3768,
 3746,
 4043,
 3759,
 4043,
 4040,
 3755,
 4091,
 4091,
 4091,
 4073,
 4072,
 4073,
 3790,
 4128,
 4093,
 4138,
 4201,
 4183,
 4183,
 4183,
 3861,
 3861,
 4319,
 3914,
 3940,
 3939,
 3942,
 3927,
 3961,
 3962,
 3735,
 3736,
 3736,
 3735,
 3735,
 3735,
 3736,
 3736,
 3744,
 3744,
 3744,
 3744,
 3744,
 3745,
 3745,
 3745,
 3745,
 3745,
 3745,
 3745,
 3746,
 3744,
 3744,
 3745,
 3735,
 3735,
 3745,
 3745,
 3745,
 3752,
 3751,
 3744,
 3744,
 3736,
 3736,
 4000,
 4000,
 3751,
 3753,
 3754,
 3754,
 3754,
 3754,
 3751,
 3753,
 3753,
 3753,
 3753,
 3753,
 3753,
 3758,
 3758,
 3757,
 3759,
 3758,
 3756,
 3759,
 3758,
 3756,
 3757,
 3757,
 3756,
 3754,
 3753,
 3755,
 3755,
 3755,
 3755,
 4024,
 4024,
 3760,
 3761,
 3759,

In [11]:
inputofnn=[]
for i in range(37237):
    inputofnn.append([nls[nl[i]],t[title[i]],time[i]])

In [12]:
inputofnn

[[0, 0, 1210],
 [1, 1, 1962],
 [1, 2, 1963],
 [1, 2, 1963],
 [1, 3, 1962],
 [1, 2, 1963],
 [1, 4, 1962],
 [1, 1, 1962],
 [1, 5, 3773],
 [2, 6, 3763],
 [1, 5, 3765],
 [2, 7, 3757],
 [2, 7, 3757],
 [2, 8, 3755],
 [1, 9, 3765],
 [1, 9, 3765],
 [1, 9, 3851],
 [1, 9, 3851],
 [1, 5, 3784],
 [1, 5, 3779],
 [1, 5, 3851],
 [1, 9, 3947],
 [1, 9, 3947],
 [1, 9, 3841],
 [1, 9, 3841],
 [1, 5, 3959],
 [1, 5, 3895],
 [1, 5, 3977],
 [1, 9, 3982],
 [1, 9, 3982],
 [2, 10, 3745],
 [2, 10, 3745],
 [2, 10, 3745],
 [1, 9, 3744],
 [1, 9, 3768],
 [1, 9, 4052],
 [1, 9, 4052],
 [1, 5, 4049],
 [2, 7, 3760],
 [1, 9, 3768],
 [2, 11, 3746],
 [1, 9, 4043],
 [2, 7, 3759],
 [1, 9, 4043],
 [1, 5, 4040],
 [2, 6, 3755],
 [1, 9, 4091],
 [1, 9, 4091],
 [1, 5, 4091],
 [1, 9, 4073],
 [1, 5, 4072],
 [1, 9, 4073],
 [1, 9, 3790],
 [1, 5, 4128],
 [1, 5, 4093],
 [1, 5, 4138],
 [1, 9, 4201],
 [1, 9, 4183],
 [1, 9, 4183],
 [1, 5, 4183],
 [1, 9, 3861],
 [1, 9, 3861],
 [1, 5, 4319],
 [1, 5, 3914],
 [1, 5, 3940],
 [1, 5, 3939],
 [1, 5

In [13]:
outputofnn=[]
for i in range(37237):
    outputofnn.append([org[i]])

In [14]:
outputofnn

[[4],
 [4],
 [4],
 [4],
 [3],
 [4],
 [3],
 [4],
 [2],
 [4],
 [2],
 [4],
 [4],
 [4],
 [3],
 [3],
 [3],
 [3],
 [2],
 [2],
 [2],
 [3],
 [3],
 [3],
 [3],
 [2],
 [2],
 [2],
 [3],
 [3],
 [3],
 [3],
 [3],
 [3],
 [3],
 [3],
 [3],
 [2],
 [4],
 [3],
 [3],
 [3],
 [4],
 [3],
 [2],
 [4],
 [3],
 [3],
 [2],
 [3],
 [2],
 [3],
 [3],
 [2],
 [2],
 [2],
 [3],
 [3],
 [3],
 [2],
 [3],
 [3],
 [2],
 [2],
 [2],
 [2],
 [2],
 [2],
 [2],
 [2],
 [3],
 [2],
 [3],
 [3],
 [3],
 [3],
 [2],
 [2],
 [2],
 [3],
 [3],
 [3],
 [3],
 [3],
 [3],
 [3],
 [3],
 [2],
 [3],
 [3],
 [2],
 [3],
 [3],
 [3],
 [3],
 [3],
 [3],
 [3],
 [3],
 [4],
 [4],
 [4],
 [4],
 [2],
 [3],
 [3],
 [3],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [3],
 [3],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [4],
 [3],
 [3],
 [3],
 [3],
 [4],
 [2],
 [4],
 [2],
 [3],
 [2],
 [4],
 [3],
 [3],
 [2],
 [3],
 [4],
 [4]

In [15]:
import sys

class ProgressBar():

    def __init__(self, max_steps):
        self.max_steps = max_steps
        self.current_step = 0
        self.progress_width = 50

    def update(self, step=None):
        self.current_step = step

        num_pass = int(self.current_step * self.progress_width / self.max_steps) + 1
        num_rest = self.progress_width - num_pass 
        percent = (self.current_step+1) * 100.0 / self.max_steps 
        progress_bar = '[' + '■' * (num_pass-1) + '▶' + '-' * num_rest + ']'
        progress_bar += '%.2f' % percent + '%' 
        if self.current_step < self.max_steps - 1:
            progress_bar += '\r' 
        else:
            progress_bar += '\n' 
        sys.stdout.write(progress_bar) 
        sys.stdout.flush()
        if self.current_step >= self.max_steps:
            self.current_step = 0
            print

In [16]:
class NeuralNetwork():
    def __init__(self): 
        #converting weights to a 3 by 1 matrix with values from -1 to 1 and mean of 0
        self.synaptic_weights1 = 2 * np.random.random((3, 2)) - 1
        self.synaptic_weights2 = 2 * np.random.random((2, 1)) - 1
    def sigmoid(self, x):
        #applying the sigmoid function
        return 1 / (1 + np.exp(-x))
    def sigmoid_derivative(self, x):
        #computing derivative to the Sigmoid function
        return x * (1 - x)
    def train(self, training_inputs, training_outputs,training_iterations,learning_rate):
        #training the model to make accurate predictions while adjusting weights continually
        max_batchs = 300
        progress_bar = ProgressBar(training_iterations)
        for iteration in range(training_iterations):
            #siphon the training data via  the neuron
            a1,output = self.think(training_inputs)
            #computing error rate for back-propagation
            error = training_outputs - output
            #performing weight adjustments
            adjustments2 = np.dot(a1.T, error * self.sigmoid_derivative(output))
            self.synaptic_weights2 += adjustments2*learning_rate
            adjustments1 = np.dot(training_inputs.T, error * self.sigmoid_derivative(a1))
            self.synaptic_weights1 += adjustments1*learning_rate
            progress_bar.update(iteration)
    def think(self, inputs):
        #passing the inputs via the neuron to get output   
        #converting values to floats
        inputs = inputs.astype(float)
        a1 = self.sigmoid(np.dot(inputs, self.synaptic_weights1))
        output = self.sigmoid(np.dot(a1, self.synaptic_weights2))
        return a1,output

In [19]:
if __name__ == "__main__":
    #initializing the neuron class
    neural_network = NeuralNetwork()
    print("Beginning Randomly Generated Weights1: ")
    print(neural_network.synaptic_weights1)
    print("Beginning Randomly Generated Weights2: ")
    print(neural_network.synaptic_weights2)
    #training data consisting of 4 examples--3 input values and 1 output
    training_inputs = np.array(inputofnn)
    training_outputs = np.array(outputofnn)/4
    #training taking place
    neural_network.train(training_inputs, training_outputs, 10000,1)
    print("Ending Weights1 After Training: ")
    print(neural_network.synaptic_weights1)
    print("Ending Weights2 After Training: ")
    print(neural_network.synaptic_weights2)

Beginning Randomly Generated Weights1: 
[[-0.2998163   0.94828191]
 [ 0.2113401  -0.98924117]
 [ 0.56430934  0.58194473]]
Beginning Randomly Generated Weights2: 
[[ 0.50156944]
 [-0.34782488]]
[■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■▶]100.00%
Ending Weights1 After Training: 
[[-0.2998163   0.94828191]
 [ 0.2113401  -0.98924117]
 [ 0.56430934  0.58194473]]
Ending Weights2 After Training: 
[[1603.15377093]
 [1602.30437661]]


In [20]:
if __name__ == "__main__":
    user_input_one = str(input("NE_LABEL: "))
    user_input_two = str(input("ALARM_TITLE_TEXT: "))
    user_input_three = str(input("EVENT_TIME: "))
    print("Considering New Situation: ", user_input_one, user_input_two, user_input_three)
    print("New Output data: ")
    print(int(float(neural_network.think(np.array([user_input_one, user_input_two, user_input_three]))[1])*4))
print("Wow, we did it!")

NE_LABEL:  5
ALARM_TITLE_TEXT:  23
EVENT_TIME:  44333


Considering New Situation:  5 23 44333
New Output data: 
4
Wow, we did it!
