In [76]:
import numpy as np
class NeuralNetwork():
    def __init__(self): 
        #converting weights to a 3 by 1 matrix with values from -1 to 1 and mean of 0
        self.synaptic_weights1 = 2 * np.random.random((5, 2)) - 1
        self.synaptic_weights2 = 2 * np.random.random((2, 1)) - 1
    def sigmoid(self, x):
        #applying the sigmoid function
        return 1 / (1 + np.exp(-x))
    def sigmoid_derivative(self, x):
        #computing derivative to the Sigmoid function
        return x * (1 - x)
    def train(self, training_inputs, training_outputs,training_iterations,learning_rate):
        #training the model to make accurate predictions while adjusting weights continually
        for iteration in range(training_iterations):
            #siphon the training data via  the neuron
            a1,output = self.think(training_inputs)
            #computing error rate for back-propagation
            error = training_outputs - output
            #performing weight adjustments
            adjustments2 = np.dot(a1.T, error * self.sigmoid_derivative(output))
            self.synaptic_weights2 += adjustments2*learning_rate
            adjustments1 = np.dot(training_inputs.T, error * self.sigmoid_derivative(a1))
            self.synaptic_weights1 += adjustments1*learning_rate
    def think(self, inputs):
        #passing the inputs via the neuron to get output   
        #converting values to floats
        inputs = inputs.astype(float)
        a1 = self.sigmoid(np.dot(inputs, self.synaptic_weights1))
        output = self.sigmoid(np.dot(a1, self.synaptic_weights2))
        return a1,output
if __name__ == "__main__":
    #initializing the neuron class
    neural_network = NeuralNetwork()
    print("Beginning Randomly Generated Weights1: ")
    print(neural_network.synaptic_weights1)
    print("Beginning Randomly Generated Weights2: ")
    print(neural_network.synaptic_weights2)
    #training data consisting of 4 examples--3 input values and 1 output
    training_inputs = np.array([[1,2,3,4,5],
                                [2,4,8,10,12],
                                [1,2,4,8,16],
                                [1,3,9,27,81],
                                [19,14,13,12,4]])
    training_outputs = np.array([[1,1,1,1,0]]).T
    #training taking place
    neural_network.train(training_inputs, training_outputs, 1000000,0.1)
    print("Ending Weights1 After Training: ")
    print(neural_network.synaptic_weights1)
    print("Ending Weights2 After Training: ")
    print(neural_network.synaptic_weights2)

Beginning Randomly Generated Weights1: 
[[ 0.62524395  0.3573533 ]
 [-0.26837848  0.03149603]
 [-0.1054953   0.77541752]
 [-0.02005242  0.69832526]
 [ 0.59070352 -0.50762509]]
Beginning Randomly Generated Weights2: 
[[-0.13348333]
 [-0.55771757]]
Ending Weights1 After Training: 
[[0.82955677 0.53272616]
 [0.14068876 0.38242576]
 [0.50910637 1.3185443 ]
 [0.79931357 1.4674952 ]
 [1.61507398 0.55760202]]
Ending Weights2 After Training: 
[[0.90958853]
 [0.47670605]]


In [2]:
if __name__ == "__main__":
    user_input_one = str(input("User Input One: "))
    user_input_two = str(input("User Input Two: "))
    user_input_three = str(input("User Input Three: "))
    user_input_four = str(input("User Input Four: "))
    user_input_five = str(input("User Input Five: "))
    print("Considering New Situation: ", user_input_one, user_input_two, user_input_three,user_input_four,user_input_five)
    print("New Output data: ")
    print(neural_network.think(np.array([user_input_one, user_input_two, user_input_three,user_input_four,user_input_five])))
print("Wow, we did it!")

KeyboardInterrupt: Interrupted by user